server:
    port: 8080
    
spring:
  application:
    name: baseline-service-gam
  cloud:
    config:
      uri: http://localhost:8888
    
security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  threadpool:
    default:
      coreSize: 35
  command:
    createRevenueGrid:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
          semaphore:
            maxConcurrentRequests: 500
      circuitBreaker:
        sleepWindowInMilliseconds: 5000
